export const ROLE_PERMISSIONS: Record<string, string[]> = {
  super_admin: [
    'manage_users',
    'manage_roles',
    'manage_system_settings',
    'view_audit_logs',
    'delete_audit_logs',
    'manage_branches',
    'manage_departments',
    'manage_wards',
    'manage_staff',
    'approve_staff_requests',
    'view_all_reports',
    'manage_billing',
    'manage_inventory',
    'manage_pharmacy',
    'manage_lab',
    'manage_radiology',
    'manage_appointments',
    'manage_medical_records',
    'manage_patients',
    'manage_notifications',
  ],
  admin: [
    'manage_users',
    'manage_staff',
    'approve_staff_requests',
    'manage_branches',
    'manage_departments',
    'manage_wards',
    'view_all_reports',
    'manage_billing',
    'manage_inventory',
    'manage_pharmacy',
    'manage_lab',
    'manage_radiology',
    'manage_appointments',
    'manage_medical_records',
    'manage_patients',
    'manage_notifications',
  ],
  doctor: [
    'view_own_profile',
    'update_own_profile',
    'view_own_appointments',
    'update_own_availability',
    'view_own_patients',
    'create_medical_records',
    'update_own_medical_records',
    'create_prescriptions',
    'view_lab_results',
    'view_radiology_results',
    'request_lab_tests',
    'request_radiology_tests',
    'admit_patients',
    'discharge_patients',
    'transfer_patients',
    'view_patient_medical_records',
  ],
  nurse: [
    'view_own_profile',
    'update_own_profile',
    'view_ward_patients',
    'update_patient_vitals',
    'administer_medications',
    'view_medical_records',
    'create_nursing_notes',
    'manage_admissions',
    'manage_bed_assignments',
  ],
  receptionist: [
    'view_own_profile',
    'update_own_profile',
    'manage_appointments',
    'check_in_patients',
    'manage_patient_registration',
    'view_patient_profiles',
    'manage_bed_assignments',
    'manage_admissions',
    'view_doctors',
    'view_departments',
  ],
  pharmacist: [
    'view_own_profile',
    'update_own_profile',
    'manage_medicines',
    'manage_inventory',
    'process_prescriptions',
    'view_prescriptions',
    'update_prescription_status',
    'manage_pharmacy_sales',
    'view_low_stock',
    'view_expiring_medicines',
  ],
  laboratory: [
    'view_own_profile',
    'update_own_profile',
    'manage_lab_tests',
    'manage_lab_categories',
    'view_lab_requests',
    'update_lab_request_status',
    'enter_lab_results',
    'view_pending_requests',
  ],
  radiologist: [
    'view_own_profile',
    'update_own_profile',
    'manage_radiology_tests',
    'view_radiology_requests',
    'update_radiology_request_status',
    'enter_radiology_results',
    'view_pending_requests',
  ],
  accountant: [
    'view_own_profile',
    'update_own_profile',
    'manage_billing',
    'manage_payments',
    'generate_receipts',
    'process_refunds',
    'view_revenue_reports',
    'view_patient_statements',
    'manage_insurance',
  ],
  ambulance_driver: [
    'view_own_profile',
    'update_own_profile',
    'view_assigned_trips',
    'update_trip_status',
  ],
  patient: [
    'view_own_profile',
    'update_own_profile',
    'view_own_appointments',
    'create_appointments',
    'view_own_medical_records',
    'view_own_prescriptions',
    'view_own_bills',
    'view_own_insurance',
    'view_notifications',
  ],
};

export const getPermissionsForRole = (role: string): string[] => {
  return ROLE_PERMISSIONS[role] || [];
};

export const hasPermission = (role: string, permission: string): boolean => {
  const permissions = ROLE_PERMISSIONS[role] || [];
  return permissions.includes(permission);
};